services:
  - type: web
    name: template-api-go
    env: go
    buildCommand: go build -o app
    startCommand: ./app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: template-db
          property: connectionString
      - key: PORT
        value: 8080
databases:
  - name: template-db
